### ISSUE TITLE
List status of all local repos [matching pattern X]

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/project-dadmin#30]
Command: `dadmin status -o <org> -r <regex>`

**Comment by snomos** [comment]
If -o or -r are not specified, it should fetch all local repos unconditionally.

There should be various levels of details:

- default: two columns + repo name; the columns:
    - uncommitted changes (# of modified files? Unresolved merge conflicts must be highlighted!)
    - committed changes not pushed, and if so, how many
- more verbose:
    - as above + modified files for each repo
- most verbose:
    - as more verbose + diff for each modified file

In all cases there should be a summary at the end, containing:

- no. of repos with uncommitted changes
- no. of repos with unpushed commits
