### ISSUE TITLE
Transfer ownership of all repositories [match pattern X]

### ISSUE THREAD

**Issue by lenguyenthanh** [divvun/project-dadmin#33]
Command: `dadmin transfer -o <org> -r <regex> -n<new-org>`

This commands need a confirmation prompt.

**Comment by snomos** [comment]
This operation is critical, since the plan is that we start out with all repos in GiellaLTTmp, where we prepare them, and when we are ready to go public, we 1) transfer the repos to GiellaLT, and 2) make them public.
