### ISSUE TITLE
Check out branch X for all local repos [matching regex]

### ISSUE THREAD

**Issue by snomos** [divvun/project-dadmin#51]

**Comment by lenguyenthanh** [comment]
@snomos, I'm working on this issue atm. I wonder does this command checkout only local branch or it also has ability to fetch, pull and checkout remote branch?

My suggestion is: we add an option for checkout remote branch.

So our command will look like: `dadmin checkout -o <org> -r <regex> --branch <branch> --remote`

`--remote` is an option, if we include it, dadmin will try to look up for remote branches.

**Comment by snomos** [comment]
> `--remote` is an option, if we include it, dadmin will try to look up for remote branches.

Sounds good! 👍
