### ISSUE TITLE
dadmin apply --script <script>should pass target repo argument to script

### ISSUE THREAD

**Issue by snomos** [divvun/project-dadmin#90]
dadmin apply --script <script>should pass target repo argument to script, so that in e.g. a shell script, `$1` holds the absolute path to the target repo at hand. From the absolute path it is easy to extract various bits of information useful to the script, like language code, repo name, path to repo, etc.

Without this information the script is much restricted in what it can do.

**Comment by lenguyenthanh** [comment]
@snomos dadmin execute the script directly inside repositories directory. So you can do almost any thing without passing absolute path to the script. For example you can get the absolute path by `pwd`.

**Comment by snomos** [comment]
ah, ok :)
